apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: myapp-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: your-dockerhub-username/myapp:latest
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: "production"